---
title : ISTA 320 Final
author: Robert Lopez  
email : rlopez4747@email.arizona.edu
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# loading data and libraries
library(tidyverse)
library(ggplot2)
library(reshape2)
library(dplyr)
library(knitr)
performance_df <- read_csv('StudentsPerformance.csv')

# remove race/ethnic column, we are not gonna use it. 
performance_df <- performance_df %>%
  select(-`race/ethnicity`)

# get only the top scores
top_scores <- performance_df %>%
  group_by(`math score`) %>% 
  summarize(total_obs = n()) %>%
  top_n(5)

# get rid of spaces and apostrophes 
performance_df$`parental level of education` <- performance_df$`parental level of education` %>%
  str_replace('\\s', '_') %>%
  str_remove('[\']')
```

Hypothesis One: Reading scores are higher than both writing and math scores.
```{r, include = FALSE}
performance_melted <- performance_df %>%
  select(-`parental level of education`, -lunch, -`test preparation course`, -gender)

performance_melted <- melt(as.data.frame(performance_melted))
```

The following histograms show the scores from 90 percent to 100 percent. The reading scores have the most 100 percents. This means that this exam gets the higher scores overall. It must be easier. 
```{r, eval=TRUE}
ggplot(performance_melted %>% filter(value > 90),
       aes( x = value,
            fill = variable)) +
  geom_bar() +
  facet_wrap(~variable)
```